name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Install Lua
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4 liblua5.4-dev

      - name: Build
        run: zig build

      - name: Run Tests
        run: zig build test

      - name: Build Release
        run: zig build -Drelease-safe

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Run Zig Format Check
        run: zig fmt --check src/
